//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WCFservice", ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFservice/IService/DownloadFile", ReplyAction="WCFservice/IService/DownloadFileResponse")]
        System.IO.Stream DownloadFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFservice/IService/DownloadFile", ReplyAction="WCFservice/IService/DownloadFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFservice/IService/GetStatus", ReplyAction="WCFservice/IService/GetStatusResponse")]
        bool GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFservice/IService/GetStatus", ReplyAction="WCFservice/IService/GetStatusResponse")]
        System.Threading.Tasks.Task<bool> GetStatusAsync();
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (FileTransferRequest) сообщения FileTransferRequest не соответствует значению по умолчанию (UploadFile).
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WCFservice/IService/UploadFile")]
        void UploadFile(ServerConsole.ServiceReference1.FileTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WCFservice/IService/UploadFile")]
        System.Threading.Tasks.Task UploadFileAsync(ServerConsole.ServiceReference1.FileTransferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileTransferRequest", WrapperNamespace="WCFservice", IsWrapped=true)]
    public partial class FileTransferRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WCFservice")]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WCFservice", Order=0)]
        public System.IO.Stream Data;
        
        public FileTransferRequest() {
        }
        
        public FileTransferRequest(string fileName, System.IO.Stream Data) {
            this.fileName = fileName;
            this.Data = Data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ServerConsole.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServerConsole.ServiceReference1.IService>, ServerConsole.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream DownloadFile(string fileName) {
            return base.Channel.DownloadFile(fileName);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string fileName) {
            return base.Channel.DownloadFileAsync(fileName);
        }
        
        public bool GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<bool> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ServerConsole.ServiceReference1.IService.UploadFile(ServerConsole.ServiceReference1.FileTransferRequest request) {
            base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string fileName, System.IO.Stream Data) {
            ServerConsole.ServiceReference1.FileTransferRequest inValue = new ServerConsole.ServiceReference1.FileTransferRequest();
            inValue.fileName = fileName;
            inValue.Data = Data;
            ((ServerConsole.ServiceReference1.IService)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ServerConsole.ServiceReference1.IService.UploadFileAsync(ServerConsole.ServiceReference1.FileTransferRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task UploadFileAsync(string fileName, System.IO.Stream Data) {
            ServerConsole.ServiceReference1.FileTransferRequest inValue = new ServerConsole.ServiceReference1.FileTransferRequest();
            inValue.fileName = fileName;
            inValue.Data = Data;
            return ((ServerConsole.ServiceReference1.IService)(this)).UploadFileAsync(inValue);
        }
    }
}
